### ISSUE TITLE
Is there any way to save transparent png images?

### ISSUE THREAD

**Issue by winstywang** [ShapeNet/shapenet-viewer#2]

**Comment by angelxuanchang** [comment]
This appears to be OS dependent due to dependencies in the jMonkeyEngine framework on which this viewer is based.  We found that Mac OS X renders transparent png images while windows and ubuntu linux do not render transparency.   This was true as of jme 3.0 - we recently updated to jme 3.1 so this behavior may have changed.

**Comment by kealennieh** [comment]
Does this problem exist now? I've already installed the software. It seems this problem isn't tackled.
